# frozen_string_literal: true

require 'rake/testtask'
require_relative 'src/application'

task default: :test

desc 'Run JSON Data Sorter'
Rake::Task.define_task(:run_json_data_sorter) do
  puts 'Provide the directory name you put the JSON file in'
  dirname = $stdin.gets&.chomp&.strip

  puts 'Provide the filename of which JSON data name you would like to sort'
  filename = $stdin.gets&.chomp&.strip

  puts 'Provide asc(default) or desc you would like to sort key-value in'
  order = $stdin.gets&.chomp&.strip

  params = { dirname:, filename:, order: }.reject { |_, value| value&.empty? }

  Application.run(**params)
end

desc 'Run all tests'
Rake::TestTask.new do |task|
  task.pattern = File.join('.', '**', '*_test.rb')
end
